---
- name: Build and Deploy todolist-api 
  hosts: app
  vars:
    ci_cd_namespace: <YOUR_NAME>-ci-cd
    dev_namespace: <YOUR_NAME>-dev
    test_namespace: <YOUR_NAME>-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier